0306191405_HoDucDuy/0306191405_HoDucDuy/Controllers/FeedbackController.cs
using _0306191405_HoDucDuy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _0306191405_HoDucDuy.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly MinicsContext _context;

        public FeedbackController(MinicsContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> TestimonialAsync()
        {
            if (Request.Cookies["isAdmin"] == "True" && Request.Cookies["status"] == "True")
            {
                return RedirectToAction("Dashboard", "Home", new { area = "Admin" });
            }
            ViewBag.Us = Request.Cookies["user"];
            ViewBag.Testimonial = "active";
            ViewData["InfoShops"] = await _context.InfoShops.ToListAsync();
            ViewData["Testimonials"] = await _context.Testimonials.Where(c => c.Status == true).ToListAsync();
            return View();
        }

        public async Task<IActionResult> WhyAsync()
        {
            if (Request.Cookies["isAdmin"] == "True" && Request.Cookies["status"] == "True")
            {
                return RedirectToAction("Dashboard", "Home", new { area = "Admin" });
            }
            ViewBag.Us = Request.Cookies["user"];
            ViewBag.Why = "active";
            ViewData["InfoShops"] = await _context.InfoShops.ToListAsync();
            ViewData["ReasonForChoices"] = await _context.ReasonForChoices.ToListAsync();
            return View();
        }
    }
}

0306191405_HoDucDuy/0306191405_HoDucDuy/Controllers/ProductController.cs
using _0306191405_HoDucDuy.Areas.Admin.Models;
using _0306191405_HoDucDuy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;
namespace _0306191405_HoDucDuy.Controllers
{
    public class ProductController : Controller
    {
        private readonly MinicsContext _context;

        public ProductController(MinicsContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ProductAsync(int? page, string name, int type)
        {
            if (Request.Cookies["isAdmin"] == "True" && Request.Cookies["status"] == "True")
            {
                return RedirectToAction("Dashboard", "Home", new { area = "Admin" });
            }
            //var produtGroup = _context.Rates.GroupBy(x => x.ProductId)
            //                .Select(x => new { id = x.Key, star = x.Count() });

        
            ViewBag.Us = Request.Cookies["user"];
            ViewBag.Product = "active";
            ViewData["InfoShops"] = await _context.InfoShops.ToListAsync();
            ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes.Where(c => c.Status == true), "Id", "Name", type);    
            ViewData["Rates"] = await _context.Rates.ToListAsync();
            ViewBag.type = type;
            ViewBag.search = name;
            if (type != 0)
            {
                if (name != null)
                {
                    return View(_context.Products.Where(c => c.Name.Contains(name)).Where(c => c.ProductTypeId == type).Where(c => c.status == true).OrderByDescending(s => s.Id).ToList().ToPagedList(pageNumber: page ?? 1, pageSize: 9));
                }
                return View(_context.Products.Where(c => c.ProductTypeId == type).Where(c => c.status == true).OrderByDescending(s => s.Id).ToList().ToPagedList(pageNumber: page ?? 1, pageSize: 9));
            }
            if (name != null)
            {
                return View(_context.Products.Where(c=>c.Name.Contains(name)).Where(c => c.status == true).OrderByDescending(s => s.Id).ToList().ToPagedList(pageNumber: page ?? 1, pageSize: 9));
            }            
            return View(_context.Products.Where(c => c.status == true).OrderByDescending(s => s.Id).ToList().ToPagedList(pageNumber: page ?? 1, pageSize: 9));
        }

        public async Task<IActionResult> DetailAsync(int? page, int? id)
        {
            if (Request.Cookies["isAdmin"] == "True" && Request.Cookies["status"] == "True")
            {
                return RedirectToAction("Dashboard", "Home", new { area = "Admin" });
            }
            ViewBag.Us = Request.Cookies["user"];
            ViewBag.Product = "active";
            ViewData["Rates"] = await _context.Rates.ToListAsync();
            ViewData["RatesById"] = _context.Rates.Include(c => c.Account).Where(c => c.ProductId == id).ToList().ToPagedList(pageNumber: page ?? 1, pageSize: 5);
            ViewData["InfoShops"] = await _context.InfoShops.ToListAsync();
            ViewData["id"] = Request.Cookies["id"];
            if (id == null)
            {
                return NotFound();
            }
            var product = await _context.Products
               .Include(p => p.ProductType)
               .FirstOrDefaultAsync(m => m.Id == id);
            ViewData["Products"] = await _context.Products.Where(c => c.status == true).Where(c => c.ProductTypeId == product.ProductTypeId).OrderByDescending(s => s.Id).ToListAsync();
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> AddRate(int ProductId, int Star, string Descrition)
        {

            if (Request.Cookies["isAdmin"] == "True" && Request.Cookies["status"] == "True")
            {
                return RedirectToAction("Dashboard", "Home", new { area = "Admin" });
            }
            if (Request.Cookies["isAdmin"] != "False" || Request.Cookies["status"] != "True")
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.Us = Request.Cookies["user"];
            try
            {
                Rate rate_new = new Rate();
                rate_new.AccountId = int.Parse(Request.Cookies["id"]);
                rate_new.ProductId = ProductId;
                rate_new.Star = Star;
                rate_new.Description = Descrition;
                rate_new.Time = DateTime.Now;
                _context.Add(rate_new);
                await _context.SaveChangesAsync();
                return RedirectToAction("detail", new { id = ProductId });
            }
            catch
            {
                return NotFound();
            }
        }
    }
}

0306191405_HoDucDuy/0306191405_HoDucDuy/Views/Shared/_CSSPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- bootstrap core css -->
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<!-- fonts style -->
<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">   <!-- range slider -->
<!-- font awesome style -->
<link href="~/css/font-awesome.min.css" rel="stylesheet" />
<!-- Custom styles for this template -->
<link href="~/css/style.css" rel="stylesheet" />
<!-- responsive style -->
<link href="~/css/responsive.css" rel="stylesheet" />

0306191405_HoDucDuy/0306191405_HoDucDuy/Views/Shared/_JSPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- jQery -->
<script src="~/lib/jquery/dist/jquery.js"></script>
<!-- bootstrap js -->
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<!-- custom js -->
<script src="~/js/custom.js"></script>
<script src="~/js/ion.rangeSlider.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

0306191405_HoDucDuy/0306191405_HoDucDuy/Views/Shared/_Layout.cshtml
@{
    IEnumerable<_0306191405_HoDucDuy.Areas.Admin.Models.InfoShop> infoShops = ViewData["InfoShops"] as IEnumerable<_0306191405_HoDucDuy.Areas.Admin.Models.InfoShop>;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <link rel="icon" href="~/images/fevicon.png" type="image/gif" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>@ViewData["Title"]</title>

    <partial name="_CSSPartial" />
    @RenderSection("CSS", required: false)
</head>
<body class="@ViewData["SubPage"]">

    <div class="hero_area">
        @foreach (var item in infoShops)
        {
            <!-- header section strats -->
            <header class="header_section">
                <div class="header_top">
                    <div class="container-fluid">
                        <div class="top_nav_container">
                            <div class="contact_nav">
                                <a href="">
                                    <i class="fa fa-phone" aria-hidden="true"></i>
                                    <span>
                                        Call :  @Html.DisplayFor(modelItem => item.Phone)
                                    </span>
                                </a>
                                <a href="@Html.DisplayFor(modelItem => item.Email)">
                                    <i class="fa fa-envelope" aria-hidden="true"></i>
                                    <span>
                                        Email :  @Html.DisplayFor(modelItem => item.Email)
                                    </span>
                                </a>
                            </div>
                            <form asp-controller="Product" asp-action="Product" class="search_form" >
                                <input type="number" name="type" value="@ViewBag.type" hidden/>
                                <input type="text" class="form-control" value="@ViewBag.search" placeholder="Search here..." name="name">
                                <button class="" type="submit">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </form>
                            <div class="user_option_box">
                                @if (ViewBag.Us != null)
                                {
                                <a class="account-link" asp-controller="user" asp-action="info">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                    <span>
                                        @ViewBag.Us
                                    </span>
                                </a>
                                }
                                else
                                {
                                    <a class="account-link" asp-controller="home" asp-action="login">
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                        <span>
                                            Login
                                        </span>
                                    </a>
                                }
                                <a class="cart-link" asp-controller="cart" asp-action="cart">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    <span>
                                        Cart
                                    </span>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="header_bottom">
                    <div class="container-fluid">
                        <nav class="navbar navbar-expand-lg custom_nav-container ">
                            <a class="navbar-brand" asp-controller="home" asp-action="index">
                                <span>
                                    Minics
                                </span>
                            </a>

                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class=""> </span>
                            </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ">
                                    <li class="nav-item  @ViewBag.Index">
                                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item  @ViewBag.About">
                                        <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                                    </li>
                                    <li class="nav-item  @ViewBag.Product">
                                        <a class="nav-link" asp-controller="Product" asp-action="Product">Products</a>
                                    </li>
                                    <li class="nav-item  @ViewBag.Why">
                                        <a class="nav-link" asp-controller="Feedback" asp-action="Why">Why Us</a>
                                    </li>
                                    <li class="nav-item  @ViewBag.Testimonial">
                                        <a class="nav-link" asp-controller="Feedback" asp-action="Testimonial">Testimonial</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </header>
            <!-- end header section -->
            @RenderBody()
            <!-- end client section -->
            <!-- info section -->
            <section class="info_section ">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="info_contact">
                                <h5>
                                    <a href="" class="navbar-brand">
                                        <span>
                                            Minics
                                        </span>
                                    </a>
                                </h5>
                                <p>
                                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                                    @Html.DisplayFor(modelItem => item.Address)
                                </p>
                                <p>
                                    <i class="fa fa-phone" aria-hidden="true"></i>
                                    @Html.DisplayFor(modelItem => item.Phone)
                                </p>
                                <p>
                                    <i class="fa fa-envelope" aria-hidden="true"></i>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="info_info">
                                <h5>
                                    Information
                                </h5>
                                <p>
                                    @Html.DisplayFor(modelItem => item.Info)
                                </p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="info_links">
                                <h5>
                                    Useful Link
                                </h5>
                                <ul>
                                    <li>
                                        <a href="index.html">
                                            Home
                                        </a>
                                    </li>
                                    <li>
                                        <a href="about.html">
                                            About
                                        </a>
                                    </li>
                                    <li>
                                        <a href="product.html">
                                            Products
                                        </a>
                                    </li>
                                    <li>
                                        <a href="why.html">
                                            Why Us
                                        </a>
                                    </li>
                                    <li>
                                        <a href="testimonial.html">
                                            Testimonial
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="info_form ">
                                <h5>
                                    Newsletter
                                </h5>
                                <form action="">
                                    <input type="email" placeholder="Enter your email">
                                    <button>
                                        Subscribe
                                    </button>
                                </form>
                                <div class="social_box">
                                    <a href="@Html.DisplayFor(modelItem => item.Facebook)">
                                        <i class="fa fa-facebook" aria-hidden="true"></i>
                                    </a>
                                    <a href="@Html.DisplayFor(modelItem => item.Twitter)">
                                        <i class="fa fa-twitter" aria-hidden="true"></i>
                                    </a>
                                    <a href="@Html.DisplayFor(modelItem => item.Instagram)">
                                        <i class="fa fa-instagram" aria-hidden="true"></i>
                                    </a>
                                    <a href="@Html.DisplayFor(modelItem => item.Youtube)">
                                        <i class="fa fa-youtube" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- end info_section -->
            <!-- footer section -->
            <footer class="footer_section">
                <div class="container">
                    <p>
                        &copy; <span id="displayYear"></span> All Rights Reserved By
                        <a href="https://html.design/">Free Html Templates</a>
                    </p>
                </div>
            </footer>
            <!-- footer section -->
        }
        <partial name="_JSPartial" />
        @RenderSection("JS", required: false)
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>